### PR TITLE
[Aveiro]Updated info and added new place 

### PR DESCRIPTION
**Pull request by Jpfonseca**
Updated info on Mercado Negro and added the Nata Lisboa place. Both in Aveiro.

### CODE REVIEW

**Comment by Jpfonseca** [comment]
@daviddias  can we get these 3 PR's merged and maybe get another mantainer, to avoid the PR's and issues to get outdated ?

**Comment by daviddias** [comment]
Are you volunteering? :)

**Comment by Jpfonseca** [comment]
> Are you volunteering? :)

Sure, why not 😛

**Comment by daviddias** [comment]
@Jpfonseca thank you! Added you.

**Comment by RichardLitt** [comment]
Woot. Sorry, I need to remove a lot of repos I watch but don't maintain. Will try to merge faster in the future. :)

**Pull request merged**
