### PR TITLE
[Copenhagen] Removed Cafe Nutid; Added The Black Diamond.

### PR DESCRIPTION
**Pull request by johncoffee**

### CODE REVIEW

**Review by Jpfonseca — COMMENTED** [review]
Any reason for the removal of `Cafe Nutid`???

**Comment by spekulatius** [comment]
> Any reason for the removal of `Cafe Nutid`???

Might have moved: https://www.tripadvisor.com/ShowUserReviews-g189541-d7790374-r672386702-Cafe_Nutid-Copenhagen_Zealand.html

**Comment by Jpfonseca** [comment]
> > Any reason for the removal of `Cafe Nutid`???
> 
> Might have moved: https://www.tripadvisor.com/ShowUserReviews-g189541-d7790374-r672386702-Cafe_Nutid-Copenhagen_Zealand.html

There aren't posts on the Facebook and Instagram since December 2019 neither reviews on TripAdvisor/Google since then. 

I will merge it, if it is open again let us know.

**Comment by johncoffee** [comment]
Closed, months back :/ I used it in the past.

**Comment by Jpfonseca** [comment]
Thanks for the input again :+1:

**Pull request merged**
